### ISSUE TITLE
Old to-do list

### ISSUE THREAD

**Issue by fluxtion** [xavery/dcue#1]
This is my old to-do list from Sourceforge that I'm pasting here for reference:

+ [ ] Allow literal ? via escape character
+ [ ] Unicode support on Windows
+ [x] Convert \u escape chars in Discogs JSON to their proper Unicode chars
+ [ ] Tidy up the code and do some inline documentation/commenting
+ [ ] Improve reliability of multi-disc parsing via empirical development of heuristics
+ [x] More detailed error reporting (perhaps warning of potential problems with output?)
+ [ ] Don't trigger naming facets when intentional
+ [ ] Offer option to create a single cue file for multi-disc releases
